#!/usr/bin/env python3
"""Generate registry schema pages from the compiled provider, offline.

Requires Go, Terraform >=1.11, Python >=3.9. No IBEE credentials are used.
Use --check to verify checked-in docs and validate every example configuration.
"""
import argparse
import json
import os
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
ADDRESS = "registry.terraform.io/devs-ibee/ibee"


def run(args, cwd, env):
    result = subprocess.run(args, cwd=cwd, env=env, text=True, capture_output=True)
    if result.returncode:
        raise RuntimeError(f"{' '.join(args)} failed:\n{result.stdout}\n{result.stderr}")
    return result.stdout


def type_name(value):
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        if value[0] == "object":
            return "object"
        return f"{value[0]}({type_name(value[1])})"
    return "object"


def schema_lines(attributes, prefix=""):
    rows = []
    for name, attr in sorted(attributes.items()):
        full = prefix + name
        nested = attr.get("nested_type")
        kind = f"{nested['nesting_mode']}(object)" if nested else type_name(attr.get("type"))
        flags = [label for key, label in [("required", "Required"), ("optional", "Optional"), ("computed", "Read-only"), ("sensitive", "Sensitive"), ("write_only", "Write-only")] if attr.get(key)]
        if attr.get("optional") and attr.get("computed"):
            flags.remove("Read-only")
            flags.append("Defaulted")
        description = attr.get("description", "").replace("|", "\\|").replace("\n", " ")
        rows.append(f"| `{full}` | `{kind}` | {', '.join(flags)} | {description} |")
        if nested:
            rows.extend(schema_lines(nested["attributes"], full + "."))
    return rows


def page(name, block, category):
    label = {"provider": "Provider", "resources": "Resource", "data-sources": "Data Source", "actions": "Action"}[category]
    description = block.get("description", "Manage IBEE cloud resources.")
    text = ["---", 'page_title: "' + name + ' ' + label + ' - IBEE"', 'subcategory: ""', "description: |-", "  " + description.replace("\n", "\n  "), "---", "", f"# {name} ({label})", "", description, "", "<!-- Generated by scripts/generate_docs.py; edit schema descriptions in Go. -->", ""]
    if category == "provider":
        text += ["Terraform 1.11 or newer is required. Set `IBEE_TOKEN` and `IBEE_WORKSPACE_ID` in the environment.", "", '```hcl', 'terraform {', '  required_version = ">= 1.11.0"', '  required_providers {', '    ibee = { source = "devs-ibee/ibee" }', '  }', '}', '', 'provider "ibee" {}', '```', "", "Use the local development override until a signed version has been published. See the repository README for installation, billing behavior, examples, and release prerequisites.", ""]
    text += ["## Schema", "", "| Attribute | Type | Behavior | Description |", "| --- | --- | --- | --- |"]
    text += schema_lines(block.get("attributes", {}))
    if category == "actions":
        text += ["", "Requires Terraform 1.14 or later. Configure this action in an `action` block with a nested `config` block. Invoke explicitly with `terraform apply -invoke=action." + name + ".example`. Actions perform operations without storing a managed resource."]
    if category == "resources":
        text += ["", "## Import", "", "This resource supports import. Use the public resource ID unless its description specifies a composite identifier or bucket name. Review the imported plan before applying; creation-only settings and local deletion permissions cannot always be reconstructed from the API."]
    if category == "resources":
        import_ids = {
            "ibee_bucket": "BUCKET_NAME",
            "ibee_vpc_subnet": "VPC_ID/SUBNET_ID",
            "ibee_vpc_node_attachment": "VPC_ID/VM_ID",
            "ibee_firewall_rule": "FIREWALL_GROUP_ID/RULE_ID",
            "ibee_firewall_attachment": "FIREWALL_GROUP_ID/VM_ID",
            "ibee_nat_gateway": "VPC_ID/NAT_GATEWAY_ID",
            "ibee_nat_port_forwarding_rule": "VPC_ID/NAT_GATEWAY_ID/RULE_ID",
            "ibee_reserved_ip_attachment": "RESERVED_IP_ID/VM_ID",
        }
        import_id = import_ids.get(name, "RESOURCE_ID")
        if name.endswith("_vm_backup_policy"):
            import_id = "VM_ID"
        if name.endswith("_vm_volume_attachment"):
            import_id = "VM_ID/VOLUME_ID"
        text += ["", "```sh", f"terraform import {name}.example '{import_id}'", "```"]
    text += [""]
    return "\n".join(text)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    env = {k: v for k, v in os.environ.items() if not k.startswith(("IBEE_", "TF_"))}
    env.update(TF_IN_AUTOMATION="1", CHECKPOINT_DISABLE="1")
    version = json.loads(run(["terraform", "version", "-json"], ROOT, env))["terraform_version"]
    supports_actions = tuple(int(v) for v in version.split(".")[:2]) >= (1, 14)
    with tempfile.TemporaryDirectory(prefix="ibee-docs-") as temp:
        tmp = Path(temp)
        binary = tmp / "bin" / "terraform-provider-ibee"
        binary.parent.mkdir()
        run(["go", "build", "-buildvcs=false", "-o", str(binary), "."], ROOT, env)
        config = tmp / "dev.tfrc"
        config.write_text('provider_installation {\n dev_overrides { "devs-ibee/ibee" = ' + json.dumps(str(binary.parent)) + ' }\n direct {}\n}\n')
        env["TF_CLI_CONFIG_FILE"] = str(config)
        (tmp / "main.tf").write_text('terraform {\n required_providers { ibee = { source = "devs-ibee/ibee" } }\n}\n')
        schema = json.loads(run(["terraform", "providers", "schema", "-json"], tmp, env))["provider_schemas"][ADDRESS]
        expected = {ROOT / "docs" / "index.md": page("ibee", schema["provider"]["block"], "provider")}
        for key, category in [("resource_schemas", "resources"), ("data_source_schemas", "data-sources")]:
            for name, spec in schema.get(key, {}).items():
                expected[ROOT / "docs" / category / (name.removeprefix("ibee_") + ".md")] = page(name, spec["block"], category)
        stale = []
        if supports_actions:
            for name, entry in schema.get("action_schemas", {}).items():
                expected[ROOT / "docs" / "actions" / (name.removeprefix("ibee_") + ".md")] = page(name, entry["block"], "actions")
        for path, contents in expected.items():
            if args.check:
                if not path.exists() or path.read_text() != contents:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(contents)
        for directory in (ROOT / "docs/resources", ROOT / "docs/data-sources"):
            for path in directory.glob("*.md"):
                if path not in expected:
                    stale.append(str(path.relative_to(ROOT)))
        if stale:
            raise SystemExit("Documentation differs; run make docs and review: " + ", ".join(stale))
        for directory in sorted({p.parent for p in (ROOT / "examples").rglob("*.tf")}):
            if directory.name == "actions" and not supports_actions:
                continue
            run(["terraform", "validate", "-no-color"], directory, env)
        print(f"{'Checked' if args.check else 'Generated'} {len(expected)} schema pages; validated examples.")


if __name__ == "__main__":
    main()
